### ISSUE TITLE
`fiss_site_tidy` script build of fiss_site dataframe from mergin import fails due to column type mismatches

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/dff-2022#149]
Similar issue for reference last year [here](https://github.com/NewGraphEnvironment/fish_passage_skeena_2022_reporting/issues/4). I don't remember this ever being fully resolved. The problem occurs when building the [loc form](https://github.com/NewGraphEnvironment/dff-2022/blob/4ff74280a7173579efa2c02a6a3d9f737e08bf62/scripts/fiss_site_tidy.R#L89) and again when building the [site form](https://github.com/NewGraphEnvironment/dff-2022/blob/4ff74280a7173579efa2c02a6a3d9f737e08bf62/scripts/fiss_site_tidy.R#L111) site form. What is the easiest way to get around this? Other than to convert the types of every column individually. Maybe I'm missing something. When reading in the empty template using `fpr::fpr_import_hab_con(backup = F, row_empty_remove = T)`, does it need to be populated with a row of data so that R knows the column types?

**Comment by NewGraphEnvironment** [comment]
yup. we need to use a populated version. We have one in [dff](https://github.com/NewGraphEnvironment/dff-2022)

https://github.com/NewGraphEnvironment/dff-2022/blob/master/data/FDS_Template2021-01-28.xls

however - since we have a new version we may as well populate it similiar to the 2021 version.  We can keep the master here for now and just copy it over to repos.  It is already present
https://github.com/NewGraphEnvironment/dff-2022/tree/master/data/templates

Let's keep the template it in a directory called `data/inputs_raw`

it is this row of the function that checks for types.  
![image](https://github.com/NewGraphEnvironment/dff-2022/assets/46538103/91fc1ed6-b5f3-4b53-808f-9a2f6fc925fa)
